#!/usr/bin/env python
import os
import shutil
import time
import subprocess
#import sh
#from sh import rsync

def check_dir_exist(os_dir):
    if not os.path.exists(os_dir):
        print os_dir, "does not exist."
        exit(1)
# Specify what and where to backup.
backup_path = raw_input("What should be backed up today?\n")
check_dir_exist(backup_path)
print "Okay", backup_path, "will be saved."
backup_to_path = raw_input("Where to backup?\n")
check_dir_exist(backup_to_path)
subprocess.call (["cp", "-R", backup_path, backup_to_path])
subprocess.call (["ls", "-l", backup_to_path])
